# Use an official Python runtime as a parent image
FROM python:3.12-slim.
# Set the working directory in the container
WORKDIR /app
# Copy the requirements file
COPY requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Copy the application code
COPY . .
# Expose the port the application will run on
EXPOSE 8083
# Run the command to start the development server
CMD ["flask", "run", "--host=0.0.0.0"]